#!/bin/bash

: ${RESTIC_BIN:=/usr/libexec/restic/restic}
: ${RESTIC_CACHE_DIR:=/var/cache/restic}

export RESTIC_CACHE_DIR

set -a
for conf in /etc/restic/restic.conf ./restic.conf; do
	if [[ -f $conf ]]; then
		echo "* reading configuration from $conf" >&2
		. $conf
	fi
done
set +a

exec $RESTIC_BIN "$@"
